name: Helm Release

on:
  workflow_run:
    workflows:
      - "Component Build"
    types:
      - completed

jobs:
  helm-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: konstellation-io/github-workflows/.github/workflows/helm-release.yaml@fix/avoid_workflow_run_on_pr
    with:
      chart_file: helm/kdl-server/Chart.yaml
      chart_path: helm
      chart_url: http://kdl.konstellation.io
      current_major: 2
    secrets:
      pat: ${{ secrets.PATNAME }}
