name: Helm Component

on:
  pull_request:
    branches:
      - main
      - "release/v*"
    paths:
      - "helm/test-workflows-1/**/*"
      - "!helm/test-workflows-1/Chart.yaml"
      - "!helm/test-workflows-1/values.yaml"
  push:
    branches:
      - main
      - "release/v*"
    paths:
      - "helm/test-workflows-1/**/*"
      - "!helm/test-workflows-1/Chart.yaml"
      - "!helm/test-workflows-1/values.yaml"

jobs:
  helm-lint:
    uses: konstellation-io/github-workflows/.github/workflows/helm-lint.yaml@fix/avoid_workflow_run_on_pr
